language: python
python:
  - "2.7"
  - "3.5"
install:
 - pip install -r requirements.txt
 - pip install --upgrade numpy
 - pip install --upgrade cython
 - python setup.py bdist_wheel --universal
addons:
  apt:
    packages:
    - libhdf5-serial-dev
scripts: nosetests
