language: python

os:
  - linux

python:
  - "2.7"
  - "3.5"

sudo: false

before_install:
  - pip install --upgrade setuptools
  - pip install -r requirements.txt
  - pip install --upgrade numpy
  - pip install --upgrade cython

install:
  - pip install .
  - python setup.py build_ext -i
  - python setup.py bdist_wheel --universal

addons:
  apt:
    packages:
    - libhdf5-serial-dev

scripts: nosetests
