language: python
python:
  - "2.7"
  - "3.5"
install:
 - pip install -r requirements.txt
 - python setup.py bdist_wheel --universal
addons:
  apt:
    packages:
    - libhdf5-serial-dev
    - python-cython
    - python-pyh5
scripts: nosetests
