language: python

os:
  - linux
  - osx

sudo: false

addons:
  apt:
    packages:
    - libhdf5-serial-dev

python:
- 2.7
- 3.5

before_install:
  - export wheelhouse=${HOME}/wheelhouse
  - pip install --upgrade setuptools
  - pip install --upgrade cython

install:
  - pip install wheel
  - git clone https://github.com/giorgiomaccari/seqFP.git

script:
  - "./build_wheels.sh"

after_success:
  - "./push_wheels.sh"

env:
  global:
    secure: "kH9zePYDXHeUHEPFQim/A7YNv4DN7X5EWEMaXvqkHTyAOSZALCjjT9A+lGmXrDUqkV/KS6sxxLvm16GaKhq1kirVavKlvdT8XnvEzaGeVif8PiT+drThkEsAidtYh9wqJSFofHXP/tUPzENQel3YSLP1heXxQrPYqVs767GAeXvwC9Hn8Jo+FlI8VQh4yQA7WZZ8+YNQ/un9Kh1bYPJYzHWSDn/kCK4XWOMHO054wEpZX8NZiSmUsxjEthCFkFveghhsnjvKvGswJ+wnC0n5xIuy6UzmwEjm2Ni2nvhI36nC+JzSZNOaV39f0OoutjA4wgsjZ487KwWCPxxT+SEJcaRa/XEAlgeLHuzHYKSJVK4VdTtfeIERXf/x+oraeeQ+dylQo8+t7w1v2g9MG7kuFMt2DLrO10sldpHtiwEjwwLWQBGcEm/65QNTc1uF4UEJtkzMQ9/k+IU2bSi9bZptBff+IWx8Il7SgEleqa5lrX36DmWkd44dIuR2vISR+azT5yQ6D/lnhqzxaPnjOwxyEwAiO4+8+AggXUOxu0kH1iCJOo8DleZYLCH5CivDgDduEm+6ohlaP+ZTb9uneXAYPUjS8G672bS1h+QSi/rWDx1ctoypMvlyZ5zDQpFuEbfHcjEfYLC6kPk8Cup3fPJnw0YHLx3k+RcmSF1q7Vydyjk="

